org: anukesh369
app: traveller-api
service: traveller-api
frameworkVersion: '2 || 3'

custom:
  tableName: 'Traveller'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    TABLENAME: ${self:custom.tableName}
    NODE_ENV: 'production'
    REGION: 'us-east-1'
    ENDPOINT: 'https://dynamodb.us-east-1.amazonaws.com'

functions:
  api:
    handler: handler.handler
    layers: 
      - arn:aws:lambda:us-east-1:442134548185:layer:comman2:1
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: TravellerCode
            AttributeType: S
          - AttributeName: BookingId
            AttributeType: S
        KeySchema:
          - AttributeName: TravellerCode
            KeyType: HASH
          - AttributeName: BookingId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}